/*
January 4th, 2022

You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. 
The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.

Increment the large integer by one and return the resulting array of digits.

Example 2:

Input: digits = [4,3,2,1]
Output: [4,3,2,2]
Explanation: The array represents the integer 4321.
Incrementing by one gives 4321 + 1 = 4322.
Thus, the result should be [4,3,2,2].
Example 3:

Input: digits = [9]
Output: [1,0]
Explanation: The array represents the integer 9.
Incrementing by one gives 9 + 1 = 10.
Thus, the result should be [1,0].

*/
class Solution {
    public int[] plusOne(int[] digits) {
        
        if(digits[digits.length - 1] + 1 != 10) {
            digits[digits.length - 1] = digits[digits.length - 1] + 1;
            return digits;
        }
        int carry = 0;
        for(int i = digits.length - 1; i >= 0; i--) {
            if(digits[i] < 9) {
                digits[i] = digits[i] + 1;
                return digits;
            } else {
                digits[i] = 0;
            }
        }
        
        int n = digits.length;
        digits = new int[n + 1];
        digits[0] = 1;
        
        
        return digits;
    }
}
